### ISSUE TITLE
Works with three buttons, not with four

### ISSUE THREAD

**Issue by bphermansson** [openhomeautomation/esp8266-relay#1]
I've changed the code to add more buttons to control outputs on my ESP03. If I use three buttons like this it works:
  rest.button(2);
  rest.button(13);
  rest.button(12);

But if I add a fourth button with another button-line ("rest.button(14);") it doesnt work. The Gui gets messed up and the buttons won't work. 
![skarmbild fran 2015-09-01 09-26-30](https://cloud.githubusercontent.com/assets/3775861/9598410/99fb2c58-508b-11e5-91e0-f668cf69c5db.png)

**Comment by marcoschwartz** [comment]
Hello, really interesting, thanks for finding out the bug! Can you tell me which ESP board you are using? It looks like a memory problem to me, the library is quite memory-hungry :)

**Comment by bphermansson** [comment]
Hi!

I use a one like this: http://www.ebay.com/itm/1PCS-ESP8266-ESP-03-Serial-WIFI-Module-Wireless-Transceiver-Send-Receive-NEW-/381374501949?

**Comment by bphermansson** [comment]
Hi again! Think I got it! 
I changed "#define OUTPUT_BUFFER_SIZE 2000" in aREST.h, line 55, to "#define OUTPUT_BUFFER_SIZE 2200". Now it's working with four buttons. If I add another one, total five buttons, the Gui messes up like before. Quite sure the output data overflows the output buffer.

**Comment by marcoschwartz** [comment]
I think you definitely got it, it has to be linked to the output buffer. In a future revision of the library I'll make sure to resize the output buffer depending on the hardware that's being used.

**Comment by bphermansson** [comment]
Sounds great! Nice lib by the way, makes it nearly too easy to control things with a Gui and the ESP8266.

**Comment by rajbadri** [comment]
for connecting a 8 channel relay what size output buffer should be set ?

**Comment by marcoschwartz** [comment]
I still need time to find out an elegant way to integrate that into the library. In the meantime, for an 8 channel relay board you could use a size of 5000, it should be large enough.

**Comment by ghost** [comment]
Hi Marcoschwartz, Firstly, I would like to say its a brielent and eay to use library. 
I am using your code to control a relay conncted to my ESP8266.
 It works fine for about 20 minutes and then the ESP hangs. Is there a way to use the watchdog pin to reset it if it hangs?

**Comment by marcoschwartz** [comment]
@surajpearson Thanks! I haven't noticed that kind of behaviour, but sure you can include the watchdog in the loop() function to automatically reset the chip if it hangs.

**Comment by REHolt** [comment]
Hi, I like you set-up here. it works great for the project I am attempting. I like the fact that it is all self contained in the ESP8266 and does not require an external server. I don't need that for this simple application. I was set up this project on my ESP8266, and am able to control a switch using 2 buttons just as described. However, I would like to have a single switch that simply toggles the relay on and back off after a short delay. being kind of new to this, i have been unable to figure out how to modify the code to set up such a switch. 

Any chance you can provide me some pointers on how to set this up?

**Comment by ghost** [comment]
@marcoschwartz, Thanks for the email. I had already included a reset mechanism in the code, after which it works fine..

**Comment by marcoschwartz** [comment]
Great!
